# версия docker-compose
version: '3.8'

volumes:
  postgres_data:
  static_volume:


# имена и описания контейнеров, которые должны быть развёрнуты
services:
  # описание контейнера db
  db:
    # образ, из которого должен быть запущен контейнер
    image: postgres:12.4
    # volume и связанная с ним директория в контейнере
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    # адрес файла, где хранятся переменные окружения
    env_file:
      - ./.env
  web:
    image: 4dragunov/yamdb_final:latest
    restart: always
    command: gunicorn api_yamdb.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      - static_volume:/code/static


  nginx:
    image: nginx:1.19.6
    restart: always
    ports:
      - 80:80
    volumes:
      - type: volume
        source: static_volume
        target: /code/static
      - type: bind
        source: ./nginx
        target: /etc/nginx/conf.d
    depends_on:
      - web

