# версия docker-compose
version: '3.8'

volumes:
  postgres_data:
  static_volume:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: 4dragunov/yamdb_final:latest
    build: .
#    restart: always
    command: gunicorn api_yamdb.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      - static_volume:/code/static


  nginx:
    image: nginx:1.19.6
    restart: always
    ports:
      - 80:80
    volumes:
      - static_volume:/code/static
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web
